# Dictionary mapping channel display names to EPGShare01 channel IDs
channel_names = {
    "WABC (New York) ABC East": "WABC-DT.us_locals1",
    "WCBS (New York) CBS East": "WCBS-DT.us_locals1",
    "WNBC (New York) NBC East": "WNBC-DT.us_locals1",
    "WNYW (New York) FOX East": "WNYW-DT.us_locals1",
    "The CW (WPIX New York)": "WPIX-DT.us_locals1",
    "PBS 13 (WNET) New York": "WNET-DT.us_locals1",
    "A&E": "A.and.E.HD.East.us2",
    "ACC Network": "ACC.Network.us2",
    "AMC": "AMC.HD.us2",
    "American Heroes Channel": "American.Heroes.Channel.HD.us2",
    "Animal Planet": "Animal.Planet.HD.us2",
    "BBC America": "BBC.America.HD.us2",
    "BBC World News HD": "BBC.News.(North.America).HD.us2",
    "BET": "BET.HD.us2",
    "BET Her": "BET.Her.us2",
    "Big Ten Network": "Big.Ten.Network.HD.us2",
    "Bloomberg TV": "Bloomberg.HD.us2",
    "Boomerang": "Boomerang.us2",
    "Bravo": "Bravo.HD.us2",
    "Buzzr": "BUZZR.us2",
    "Cartoon Network": "Cartoon.Network.HD.us2",
    "CBS Sports Network": "CBS.Sports.Network.HD.us2",
    "Cinemax": "Cinemax.HD.us2",
    "CNBC": "CNBC.HD.us2",
    "CMT": "CMT.HD.us2",
    "CNN": "CNN.HD.us2",
    "Comedy Central": "Comedy.Central.HD.us2",
    "Cooking Channel": "Cooking.Channel.HD.us2",
    "Crime & Investigation HD": "Crime.and.Investigation.Network.HD.us2",
    "CSPAN": "CSPAN.us2",
    "CSPAN 2": "CSPAN2.us2",
    "Destination America": "Destination.America.HD.us2",
    "Discovery": "Discovery.Channel.HD.us2",
    "Discovery Family Channel": "Discovery.Family.Channel.HD.us2",
    "Discovery Life": "Discovery.Life.Channel.us2",
    "Disney Channel (East)": "Disney.Channel.HD.us2",
    "Disney Junior": "Disney.Junior.HD.us2",
    "Disney XD": "Disney.XD.HD.us2",
    "E!": "E!.Entertainment.Television.HD.us2",
    "ESPN": "ESPN.HD.us2",
    "ESPN2": "ESPNU.HD.us2",
    "ESPNews": "ESPNEWS.HD.us2",
    "ESPNU": "ESPNU.HD.us2",
    "Food Network": "Food.Network.HD.us2",
    "Fox Business Network": "Fox.Business.HD.us2",
    "FOX News Channel": "Fox.News.Channel.HD.us2",
    "FOX Sports 1": "FS1.Fox.Sports.1.HD.us2",
    "FOX Sports 2": "FS2.Fox.Sports.2.HD.us2",
    "Freeform": "Freeform.HD.us2",
    "Fuse HD": "Fuse.HD.us2",
    "FX": "FX.HD.us2",
    "FX Movie": "FX.Movie.Channel.HD.us2",
    "FXX": "FXX.HD.us2",
    "FYI": "FYI.Channel.HD.us2",
    "Golf Channel": "Golf.Channel.HD.us2",
    "Hallmark": "Hallmark.Channel.HD.us2",
    "Hallmark Drama HD": "Hallmark.Family.us2",
    "Hallmark Movies & Mysteries HD": "Hallmark.Mystery.HD.us2",
    # HBO Channels
    "HBO East": "HBO.East.us2",
    "HBO 2 East": "HBO2.HD.us2",
    "HBO Comedy HD": "HBO.Comedy.HD.us2",
    "HBO Family East": "HBO.Drama.us2",
    "HBO Signature": "HBO.Signature.HD.us2",
    "HBO Zone HD": "HBO.Zone.HD.us2",
    "HGTV": "Home.and.Garden.Television.HD.us2",
    "History": "History.HD.us2",
    "HLN": "HLN.HD.us2",
    "IFC": "IFC.HD.us2",
    "Investigation Discovery": "Investigation.Discovery.HD.us2",
    "ION Television East HD": "ION.Television.HD.us2",
    "Lifetime": "Lifetime.HD.us2",
    "LMN": "LMN.HD.us2",
    "Logo": "Logo.us2",
    "MeTV Toons": "Me.TV.Network.us2",
    "MLB Network": "MLB.Network.HD.us2",
    "MoreMAX": "MoreMax.HD.us2",
    "MotorTrend HD": "MOTORTREND.HD.us2",
    "MSNBC": "MSNBC.HD.us2",
    "MTV": "MTV.-.Music.Television.HD.us2",
    "National Geographic": "National.Geographic.HD.us2",
    "Nat Geo WILD": "National.Geographic.Wild.HD.us2",
    "NBA TV": "NBA.TV.HD.us2",
    "Newsmax TV": "Newsmax.TV.HD.us2",
    "NFL Network": "NFL.Network.HD.us2",
    "NFL Red Zone": "NFL.RedZone.HD.us2",
    "NHL Network": "NHL.Network.HD.us2",
    "Nick Jr.": "Nick.Jr.HD.us2",
    "Nickelodeon East": "Nickelodeon.HD.us2",
    "Nicktoons": "Nicktoons.us2",
    "TeenNick": "Teen.Nick.us2",
    "Outdoor Channel": "Outdoor.Channel.HD.us2",
    "OWN": "Oprah.Winfrey.Network.HD.us2",
    "Oxygen True Crime": "Oxygen.True.Crime.HD.us2",
    "ReelzChannel": "ReelzChannel.HD.us2",
    "Science": "Science.Channel.HD.us2",
    "SEC Network": "SEC.Network.HD.us2",
    "Showtime (E)": "Paramount+.with.Showtime.HD.us2",
    "SHOWTIME 2": "Showtime.2.HD.us2",
    "STARZ East": "Starz.HD.us2",
    "SundanceTV HD": "SundanceTV.HD.us2",
    "SYFY": "Syfy.HD.us2",
    "TBS": "TBS.HD.us2",
    "TCM": "Turner.Classic.Movies.HD.us2",
    "Telemundo East": "Telemundo.Satellite.Feed.us2",
    "Tennis Channel": "Tennis.Channel.HD.us2",
    "The Movie Channel East": "The.Movie.Channel.HD.us2",
    "The Weather Channel": "The.Weather.Channel.HD.us2",
    "TLC": "TLC.HD.(US).us2",
    "TNT": "TNT.HD.us2",
    "Travel Channel": "The.Travel.Channel.HD.us2",
    "truTV": "truTV.HD.us2",
    "TV One HD": "TV.ONE.HD.us2",
    "Universal Kids": "PBS.KIDS.HD.us2",
    "Univision East": "Univision.Network.HD.us2",
    "USA Network": "USA.Network.HD.us2",
    "VH1": "VH1.HD.us2",
    "VICE": "Vice.us2",
    "WE tv": "WE.tv.HD.us2"
}
