# Dictionary mapping channel display names to EPGShare01 channel IDs
channel_names = {
    "A&E": "A.and.E.US.-.Eastern.Feed.us",
    "ACC Network": "ACC.Network.us",
    "AMC": "AMC.-.Eastern.Feed.us",
    "American Heroes Channel": "American.Heroes.Channel.us",
    "Animal Planet": "Animal.Planet.US.-.East.us",
    "BBC America": "BBC.America.-.East.us",
    "BBC World News HD": "BBC.World.News.North.America.(BBCWN).us",
    "BET": "BET.-.Eastern.Feed.us",
    "BET Her": "BET.Her.us",
    "Big Ten Network": "Big.Ten.Network.us",
    "Bloomberg TV": "Bloomberg.TV.USA.us",
    "Boomerang": "Boomerang.us",
    "Bravo": "Bravo.USA.-.Eastern.Feed.us",
    "Bravo Canada": "Bravo.Canada",
    "Buzzr": "Buzzr.TV.us",
    "Cartoon Network": "Cartoon.Network.USA.-.Eastern.Feed.us",
    "CBS Sports Network": "CBS.Sports.Network.USA.us",
    "Cinemax": "Cinemax.-.Eastern.Feed.us",
    "CNBC": "CNBC.USA.us",
    "CMT": "CMT.US.-.Eastern.Feed.us",
    "CNN": "CNN.us",
    "Comedy Central": "Comedy.Central.(US).-.Eastern.Feed.us",
    "Cooking Channel": "The.Cooking.Channel.us",
    "Crime & Investigation HD": "crime-investigation-network-usa-hd/6216",
    "CSPAN": "C-SPAN.us",
    "CSPAN 2": "C-SPAN.2.us",
    "Destination America": "Destination.America.us",
    "Discovery": "Discovery.Channel.(US).-.Eastern.Feed.us",
    "Discovery Family Channel": "Discovery.Family.Channel.us",
    "Discovery Life": "Discovery.Life.Channel.us",
    "Disney Channel (East)": "Disney.-.Eastern.Feed.us",
    "Disney Junior": "Disney.Junior.USA.-.East.us",
    "Disney XD": "Disney.XD.USA.-.Eastern.Feed.us",
    "E!": "E!.Entertainment.USA.-.Eastern.Feed.us",
    "ESPN": "ESPN.us",
    "ESPN2": "ESPN2.us",
    "ESPNews": "ESPN.News.us",
    "ESPNU": "ESPNU.On.Demand.us",
    "Food Network": "Food.Network.USA.-.Eastern.Feed.us",
    "Fox Business Network": "Fox.Business.us",
    "FOX News Channel": "Fox.News.us",
    "FOX Sports 1": "Fox.Sports.1.us",
    "FOX Sports 2": "Fox.Sports.2.us",
    "Freeform": "Freeform.-.East.Feed.us",
    "Fuse HD": "FUSE.TV.-.Eastern.feed.us",
    "FX": "FX.Networks.East.Coast.us",
    "FX Movie": "FX.Movie.Channel.us",
    "FXX": "FXX.USA.-.Eastern.us",
    "FYI": "FYI.USA.-.Eastern.us",
    "Golf Channel": "Golf.Channel.USA.us",
    "Hallmark": "Hallmark.-.Eastern.Feed.us",
    "Hallmark Drama HD": "Hallmark.Drama.HDTV.(HALDRHD).us",
    "Hallmark Movies & Mysteries HD": "Hallmark.Mystery.Eastern.-.HD.us",
    "HGTV": "HGTV.USA.-.Eastern.Feed.us",
    "History": "History.Channel.US.-.Eastern.Feed.us",
    "HLN": "HLN.us",
    "IFC": "IFC.HDTV.(East).us",
    "Investigation Discovery": "Investigation.Discovery.USA.-.Eastern.us",
    "ION Television East HD": "ION..-.Eastern.Feed.us",
    "Lifetime": "Lifetime.Network.US.-.Eastern.Feed.us",
    "Lifetime Canada": "Lifetime.TV.Canada",
    "LMN": "Lifetime.Movies.-.East.us",
    "Logo": "LOGO.-.East.us",
    "MLB Network": "MLB.Network.us",
    "MoreMAX": "MoreMax..Eastern.us",
    "MotorTrend HD": "Motor.Trend.HD.us",
    "MSNBC": "MSNBC.USA.us",
    "MTV": "MTV.USA.-.Eastern.Feed.us",
    "National Geographic": "National.Geographic.US.-.Eastern.us",
    "Nat Geo WILD": "National.Geographic.Wild.us",
    "NBA TV": "NBA.TV.USA.us",
    "Newsmax TV": "NewsMax.TV.us",
    "NFL Network": "NFL.Network.us",
    "NFL Red Zone": "NFL.RedZone.us",
    "NHL Network": "NHL.Network.USA.us",
    "Nick Jr.": "Nick.Jr..-.East.us",
    "Nickelodeon East": "Nickelodeon.USA.-.East.Feed.us",
    "Nicktoons": "Nicktoons.-.East.us",
    "Outdoor Channel": "Outdoor.Channel.US.us",
    "OWN": "Oprah.Winfrey.Network.USA.Eastern.us",
    "Oxygen True Crime": "True.Crime.TV.us",
    "PBS 13 (WNET) New York": "PBS.(WNET).New.York,.NY.us",
    "ReelzChannel": "ReelzChannel.us",
    "Science": "Science.us",
    "SEC Network": "SEC.Network.us",
    "Showtime (E)": "Showtime.2.-.Eastern.us",
    "SHOWTIME 2": "Showtime.Extreme.-.Eastern.us",
    "STARZ East": "Starz.-.Eastern.us",
    "SundanceTV HD": "SundanceTV.USA.-.East.us",
    "SYFY": "Syfy.-.Eastern.Feed.us",
    "TBS": "TBS.-.East.us",
    "TCM": "Turner.Classic.Movies.USA.us",
    "TeenNick": "TeenNick.-.Eastern.us",
    "Telemundo East": "Telemundo..-.Eastern.Feed.us",
    "Tennis Channel": "The.Tennis.Channel.us",
    "The CW (WPIX New York)": "WPIX.New.York.(SUPERSTATION).us",
    "The Movie Channel East": "The.Movie.Channel.HDTV.(East).us",
    "The Weather Channel": "The.Weather.Channel.us",
    "TLC": "TLC.USA.-.Eastern.us",
    "TNT": "TNT.-.Eastern.Feed.us",
    "Travel Channel": "Travel.US.-.East.us",
    "truTV": "truTV.USA.-.Eastern.us",
    "TV One HD": "TV.One.us",
    "Universal Kids": "Universal.Kids.us",
    "Univision East": "Univision.-.Eastern.Feed.us",
    "USA Network": "USA.Network.-.East.Feed.us",
    "VH1": "VH1.-.Eastern.Feed.us",
    "VICE": "VICE.us",
    "WE tv": "WE.(Women&apos;s.Entertainment).-.Eastern.us",
    "WABC (New York) ABC East": "ABC.(WABC).New.York,.NY.us",
    "WCBS (New York) CBS East": "CBS.(WCBS).New.York,.NY.us",
    "WNBC (New York) NBC East": "NBC.(WNBC).New.York,.NY.us",
    "WNYW (New York) FOX East": "FOX.(WNYW).New.York,.NY.us"
}
